python convert_csv_to_json.py time_series_covid19_confirmed_global_rate
python convert_csv_to_json.py time_series_covid19_deaths_global_rate
python convert_csv_to_json.py time_series_covid19_confirmed_US_rate
python convert_csv_to_json.py time_series_covid19_deaths_US_rate

copy *.js H:\covid_sandbox\data\*.js
